### ISSUE TITLE
[Bug]: Crashing on New Game with Combat Gameplay Overhaul

### ISSUE THREAD

**Issue by jolly-gopher** [Monitor221hz/Pandora-Behaviour-Engine-Plus#301] opened 2024-08-29 10:25 UTC
### Check for duplicate issues

- [X] I have verified that there are no duplicate [issues](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/issues).

### Version

2.3.0-beta

### Provide Instructions on Reproducing the Problem

Running the engine with CGO enabled causes a crash with my load order when starting a new game. (Instant crash before the game can start showing the race menu.) This was not a problem in the previous version of Pandora I used (1.6.3-alpha). My crash log (attached) has a lot of mentions of "RootBehaviorGraph" and "Default_Behavior". 

Any combination of mods where CGO is enabled in Pandora will produce the crash on my end. For example: 
Simply enabling CGO, Pandora Base, and the XPMSSE Patch for Pandora.

### Provide Relevant Files

[Pandora_Output.zip](https://github.com/user-attachments/files/16797494/Pandora_Output.zip)
[crash-2024-08-29-10-18-43.log](https://github.com/user-attachments/files/16797497/crash-2024-08-29-10-18-43.log)
![Pandora-CGO-Issue](https://github.com/user-attachments/assets/09932894-3c26-4385-bf22-d60cd3b37253)

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by alexjet85** [comment] 2024-09-13 21:14
same problem here with just UESP CGO and it'z requirements installed.

**Comment by sirlach** [comment] 2024-09-18 11:52
I'm experiencing the same issue after upgrading to 2.3.0b.

**Comment by sirlach** [comment] 2024-09-24 12:24
> I'm experiencing the same issue after upgrading to 2.3.0b.

Further testing. 

1. Build (2.3.0b)  with CGO Ticked and load existing save - CTD.
2. Delete Output Directory 
3.  Build (2.3.0b) with CGO NOT Ticked and load existing save - Works fine.

**Comment by sirlach** [comment] 2024-09-26 12:09
Did some more testing with CGO enabled. 

1. v2.1.5 -> CTD
2. v2.0.4 -> CTD
3.  v1.6.3 -> Works Fine.

**Comment by Monitor221hz** [comment] 2024-10-21 23:59
> Did some more testing with CGO enabled.
> 
>     v2.1.5 -> CTD
>     v2.0.4 -> CTD
>     v1.6.3 -> Works Fine.

I've tested with v1.6.3-alpha and only CGO and it throws a critical failure. I'm unsure how to reproduce a working example on this version.

**Comment by Monitor221hz** [comment] 2024-10-22 14:46
As a temporary fix, you can hide `#1959.txt` in the _1stPerson/0_Master folder of the CGO nemesis patch. I'm looking into the cause of the issue.

**Comment by Monitor221hz** [comment] 2024-10-23 23:55
Should be fixed in v2.3.5-alpha according to my testing. Reopen this issue if it isn't.

**Closed by Monitor221hz** 2024-10-23 23:55 UTC
Labels: bug
